version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    # images: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - c_network
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    # images: wordpress
    env_file:
      - .env
    networks:
      - c_network
    volumes:
      - wp:/var/www/html/wordpress

  nginx:
    depends_on:
     - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    # images: nginx
    ports:
      - 443:443
    # - target: 8080       ## 컨테이너 내부 포트
    # published: 8080    ## 호스트OS에서 공개할 포트
    # protocol: tcp      ## 포트 프로토콜

    env_file:
      - .env
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - c_network



volumes:
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/junyopar/data/wordpress
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/junyopar/data/db

networks:
  c_network:
    driver: bridge
