version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "8080:8080"
    # - target: 8080       ## 컨테이너 내부 포트
    # published: 8080    ## 호스트OS에서 공개할 포트
    # protocol: tcp      ## 포트 프로토콜
    expose:
      - 9000
    volume:
      - test_volume: var/www

volume:
  test_volume:
