version: "3.9"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    # images: nginx
    ports:
      - "443:443"
    # - target: 8080       ## 컨테이너 내부 포트
    # published: 8080    ## 호스트OS에서 공개할 포트
    # protocol: tcp      ## 포트 프로토콜

    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - c_network

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    # images: wordpress
    env_file:
      - .env
    networks:
      - c_network
    volumes:
      - wp:var/www/wordpress
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    # images: mariadb
    env_file:
      - .env
    networks:
      - c_network
    volumes:
      - db:/var/lib/mysql

volumes:
  wp:
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress
  db:
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db

networks:
  c_network: {}
