FROM debian:buster

LABEL maintainer="junyopar"
LABEL email="42.4.junyopar@gmail.com"

RUN apt-get update
RUN apt-get install -y nginx openssl





# ENTRYPOINT ["ls;"]
# CMD ["nginx", "-g", "daemon off;"]
